-- Tabla para prueba de escaneo de cédulas colombianas (PDF417)
CREATE TABLE IF NOT EXISTS cedulas_demo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  data_cruda TEXT NOT NULL,
  cedula_parseada TEXT,
  estado TEXT DEFAULT 'sin_procesar' -- 'sin_procesar', 'procesada', 'error'
);

-- Habilitar Row Level Security
ALTER TABLE cedulas_demo ENABLE ROW LEVEL SECURITY;

-- Política temporal para desarrollo (acceso total)
CREATE POLICY "Acceso total cedulas_demo" ON cedulas_demo FOR ALL USING (true) WITH CHECK (true);

-- Índices para mejorar búsquedas
CREATE INDEX idx_cedulas_demo_created_at ON cedulas_demo(created_at DESC);
CREATE INDEX idx_cedulas_demo_cedula_parseada ON cedulas_demo(cedula_parseada);
