-- Crear tabla de inspecciones para el módulo de inspecciones
CREATE TABLE IF NOT EXISTS inspecciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  tipo TEXT NOT NULL, -- Tipo de inspección
  area TEXT,
  
  fecha_programada DATE NOT NULL,
  fecha_realizada DATE,
  
  responsable TEXT,
  
  hallazgos TEXT,
  acciones_correctivas TEXT,
  
  estado TEXT DEFAULT 'pendiente' -- 'pendiente', 'en_proceso', 'completada'
);

-- Habilitar seguridad a nivel de fila
ALTER TABLE inspecciones ENABLE ROW LEVEL SECURITY;

-- Política de acceso total (para desarrollo)
CREATE POLICY "Acceso total a inspecciones" ON inspecciones
  FOR ALL USING (true) WITH CHECK (true);

-- Insertar datos de ejemplo
INSERT INTO inspecciones (tipo, area, fecha_programada, fecha_realizada, responsable, hallazgos, acciones_correctivas, estado) VALUES
('Inspección de Seguridad Industrial', 'Planta de Producción', '2024-12-10', '2024-12-10', 'Jefe de Seguridad', 'Extintor bloqueado en zona B', 'Se despejó el área inmediatamente', 'completada'),
('Control de Calidad - Lote 450', 'Laboratorio', '2024-12-12', NULL, 'Analista QC', NULL, NULL, 'pendiente'),
('Revisión de Limpieza y Orden (5S)', 'Almacén', '2024-12-11', '2024-12-11', 'Supervisor de Almacén', 'Todo en orden', NULL, 'completada');
