-- Tabla para los líderes
CREATE TABLE IF NOT EXISTS eventos_lideres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla para las boletas
CREATE TABLE IF NOT EXISTS eventos_boletas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lider_id BIGINT REFERENCES eventos_lideres(id) ON DELETE CASCADE,
    codigo_qr UUID DEFAULT gen_random_uuid(), -- Identificador único para el QR
    consecutivo INT, -- Número legible para la boleta (ej: 1, 2, 3...)
    estado TEXT DEFAULT 'generada', -- 'generada', 'asistio'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    attended_at TIMESTAMPTZ
);

-- Política de seguridad (abierta para demo)
ALTER TABLE eventos_lideres ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acceso total lideres" ON eventos_lideres FOR ALL USING (true);

ALTER TABLE eventos_boletas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acceso total boletas" ON eventos_boletas FOR ALL USING (true);
