-- Tabla de Eventos
CREATE TABLE IF NOT EXISTS social_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    lugar TEXT,
    fecha DATE,
    hora TIME,
    fondo_url TEXT, -- URL de la imagen de fondo para las boletas
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Líderes (Actualizada con foto y datos)
CREATE TABLE IF NOT EXISTS social_lideres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    documento TEXT UNIQUE,
    telefono TEXT,
    foto_url TEXT,
    codigo_qr_personal UUID DEFAULT gen_random_uuid(), -- QR único del líder (para su carnet)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla de Boletas (Vinculada a Evento y Líder)
CREATE TABLE IF NOT EXISTS social_boletas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT REFERENCES social_eventos(id) ON DELETE CASCADE,
    lider_id BIGINT REFERENCES social_lideres(id) ON DELETE CASCADE,
    codigo_qr UUID DEFAULT gen_random_uuid(),
    consecutivo INT,
    estado TEXT DEFAULT 'generada', -- 'generada', 'usada'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    used_at TIMESTAMPTZ
);

-- Políticas de seguridad (CORREGIDAS PARA PERMITIR INSERT)
ALTER TABLE social_eventos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public events insert" ON social_eventos FOR INSERT WITH CHECK (true);
CREATE POLICY "Public events select" ON social_eventos FOR SELECT USING (true);
CREATE POLICY "Public events update" ON social_eventos FOR UPDATE USING (true);
CREATE POLICY "Public events delete" ON social_eventos FOR DELETE USING (true);

ALTER TABLE social_lideres ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public leaders insert" ON social_lideres FOR INSERT WITH CHECK (true);
CREATE POLICY "Public leaders select" ON social_lideres FOR SELECT USING (true);
CREATE POLICY "Public leaders update" ON social_lideres FOR UPDATE USING (true);
CREATE POLICY "Public leaders delete" ON social_lideres FOR DELETE USING (true);

ALTER TABLE social_boletas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public tickets insert" ON social_boletas FOR INSERT WITH CHECK (true);
CREATE POLICY "Public tickets select" ON social_boletas FOR SELECT USING (true);
CREATE POLICY "Public tickets update" ON social_boletas FOR UPDATE USING (true);
CREATE POLICY "Public tickets delete" ON social_boletas FOR DELETE USING (true);
