-- ============================================
-- MIGRACIÓN: Actualizar tabla COMPROMISOS
-- Ejecutar este script en Supabase SQL Editor
-- ============================================

-- 1. Eliminar tabla antigua si existe
DROP TABLE IF EXISTS compromisos CASCADE;

-- 2. Crear tabla con nueva estructura
CREATE TABLE compromisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id BIGINT REFERENCES revisiones(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Información del compromiso
  tipo_salida TEXT DEFAULT 'mejora', -- 'mejora', 'cambio_sgc', 'recursos'
  descripcion TEXT NOT NULL,
  objetivo TEXT,
  
  -- Responsabilidad
  responsable TEXT NOT NULL,
  area_responsable TEXT,
  
  -- Plazos
  fecha_compromiso DATE NOT NULL,
  fecha_limite DATE NOT NULL,
  fecha_cumplimiento DATE,
  
  -- Estado y seguimiento
  estado TEXT DEFAULT 'pendiente', -- 'pendiente', 'en_proceso', 'completado', 'vencido', 'cancelado'
  prioridad TEXT DEFAULT 'media', -- 'alta', 'media', 'baja'
  porcentaje_avance NUMERIC DEFAULT 0,
  
  -- Recursos
  recursos_necesarios TEXT,
  presupuesto_estimado NUMERIC,
  
  -- Evidencias
  evidencias TEXT[],
  observaciones TEXT,
  
  -- Verificación
  verificado_por TEXT,
  fecha_verificacion DATE,
  eficaz BOOLEAN
);

-- 3. Habilitar RLS
ALTER TABLE compromisos ENABLE ROW LEVEL SECURITY;

-- 4. Política de acceso total (temporal para desarrollo)
CREATE POLICY "Acceso total" ON compromisos FOR ALL USING (true) WITH CHECK (true);

-- 5. Trigger para updated_at
CREATE TRIGGER update_compromisos_updated_at 
BEFORE UPDATE ON compromisos
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 6. Índices para optimización
CREATE INDEX idx_compromisos_revision ON compromisos(revision_id);
CREATE INDEX idx_compromisos_estado ON compromisos(estado);
CREATE INDEX idx_compromisos_responsable ON compromisos(responsable);

-- 7. Crear revisión de ejemplo (si no existe)
INSERT INTO revisiones (
  titulo,
  fecha_revision,
  responsable,
  participantes,
  estado,
  analisis_auditorias,
  conclusiones_generales
) VALUES (
  'Revisión por la Dirección Q4-2024',
  '2024-12-01',
  'Gerente General',
  ARRAY['Director Comercial', 'Jefe de Calidad', 'Gerente de Producción', 'Director RRHH'],
  'en_seguimiento',
  'Se identificaron hallazgos en calibración de equipos. Acción correctiva en marcha.',
  'Sistema de Gestión funcionando adecuadamente. Se identificaron oportunidades de mejora en recursos humanos y actualización de sistemas digitales.'
)
ON CONFLICT DO NOTHING;

-- 8. Datos de demostración de compromisos
INSERT INTO compromisos (
  revision_id,
  tipo_salida,
  descripcion,
  objetivo,
  responsable,
  area_responsable,
  fecha_compromiso,
  fecha_limite,
  estado,
  prioridad,
  porcentaje_avance,
  recursos_necesarios,
  presupuesto_estimado,
  observaciones
) VALUES
(
  (SELECT id FROM revisiones ORDER BY created_at DESC LIMIT 1),
  'mejora',
  'Implementar programa de calibración preventiva de equipos de medición',
  'Reducir hallazgos de auditoría relacionados con calibración',
  'Jefe de Calidad',
  'Calidad',
  '2024-12-01',
  '2025-01-15',
  'en_proceso',
  'alta',
  60,
  'Técnico de metrología, software de gestión, calibradores externos',
  8500,
  'Primera fase completada. Inventario de equipos terminado.'
),
(
  (SELECT id FROM revisiones ORDER BY created_at DESC LIMIT 1),
  'recursos',
  'Contratar 2 inspectores de calidad adicionales',
  'Mejorar tiempos de inspección y reducir sobrecarga del equipo actual',
  'Director de RRHH',
  'Recursos Humanos',
  '2024-12-01',
  '2025-02-01',
  'pendiente',
  'alta',
  20,
  'Presupuesto para 2 salarios + beneficios',
  120000,
  'Perfil de cargo definido. Publicación de vacante en proceso.'
),
(
  (SELECT id FROM revisiones ORDER BY created_at DESC LIMIT 1),
  'cambio_sgc',
  'Actualizar procedimiento de gestión documental a sistema digital',
  'Eliminar hallazgos de documentos desactualizados',
  'Representante de Calidad',
  'Calidad',
  '2024-12-01',
  '2024-12-20',
  'en_proceso',
  'media',
  75,
  'Licencias de software, capacitación de personal',
  5000,
  'Sistema configurado. Capacitación programada para próxima semana.'
),
(
  (SELECT id FROM revisiones ORDER BY created_at DESC LIMIT 1),
  'mejora',
  'Desarrollar plan de fidelización de clientes',
  'Contrarrestar entrada de competidor con precios bajos',
  'Director Comercial',
  'Ventas',
  '2024-12-01',
  '2025-01-31',
  'en_proceso',
  'alta',
  40,
  'Equipo de marketing, presupuesto promocional',
  25000,
  'Análisis de competencia completado. Propuesta en desarrollo.'
);

-- ============================================
-- VERIFICACIÓN
-- ============================================

-- Verificar que la tabla se creó correctamente
SELECT COUNT(*) as total_compromisos FROM compromisos;

-- Ver estructura de la tabla
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'compromisos' 
ORDER BY ordinal_position;
