-- ============================================
-- SISTEMA DE GESTIÓN DE CALIDAD ISO 9001:2015
-- Schema Completo Funcional - Cláusula 9.3
-- Revisión por la Dirección
-- ============================================

-- ============================================
-- FUNCIONES BASE
-- ============================================

-- Función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ============================================
-- MÓDULOS DE ENTRADAS (9.3.2)
-- ============================================

-- 9.3.2.a) Estado de acciones de revisiones previas
-- (Vinculado a tabla compromisos con revision_id)

-- 9.3.2.b) Cambios en cuestiones externas e internas
CREATE TABLE IF NOT EXISTS gestion_cambios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_identificacion DATE NOT NULL,
  tipo_cambio TEXT NOT NULL, -- 'externo', 'interno'
  categoria TEXT, -- 'normativo', 'mercado', 'tecnologico', 'organizacional', 'competitivo', 'economico', 'social'
  
  descripcion_cambio TEXT NOT NULL,
  origen TEXT, -- De dónde viene el cambio
  impacto_sgc TEXT, -- 'alto', 'medio', 'bajo'
  
  -- Análisis
  procesos_afectados TEXT[],
  partes_interesadas_afectadas TEXT[],
  analisis_impacto TEXT,
  
  -- Acciones
  acciones_requeridas TEXT,
  responsable TEXT,
  fecha_implementacion DATE,
  
  estado TEXT DEFAULT 'identificado', -- 'identificado', 'en_analisis', 'en_implementacion', 'implementado', 'cerrado'
  evidencias TEXT[],
  observaciones TEXT
);

-- 9.3.2.c.1) Satisfacción del cliente y retroalimentación de partes interesadas

-- Encuestas de Satisfacción
CREATE TABLE IF NOT EXISTS encuestas_satisfaccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_encuesta DATE NOT NULL,
  periodo TEXT, -- 'Q1-2024', 'Nov-2024', etc.
  cliente TEXT NOT NULL,
  tipo_cliente TEXT, -- 'distribuidor', 'usuario_final', 'corporativo', 'gobierno'
  
  -- Metodología
  metodo_aplicacion TEXT, -- 'online', 'telefonica', 'presencial', 'email'
  
  -- Resultados (escala 1-5)
  calidad_producto NUMERIC,
  servicio_atencion NUMERIC,
  tiempos_entrega NUMERIC,
  precio_valor NUMERIC,
  comunicacion NUMERIC,
  resolucion_problemas NUMERIC,
  
  -- Resultado general
  satisfaccion_general NUMERIC,
  nps_score INT, -- Net Promoter Score (-100 a 100)
  
  comentarios TEXT,
  areas_mejora_identificadas TEXT,
  responsable_seguimiento TEXT,
  
  acciones_tomadas TEXT,
  estado TEXT DEFAULT 'pendiente' -- 'pendiente', 'en_analisis', 'con_acciones', 'cerrada'
);

-- PQRS ya existe como quejas_reclamos

-- 9.3.2.c.2) Grado de logro de objetivos de calidad
CREATE TABLE IF NOT EXISTS objetivos_calidad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  periodo TEXT NOT NULL, -- '2024', 'Q4-2024'
  codigo_objetivo TEXT, -- 'OC-001', 'OC-002'
  
  -- Definición del objetivo
  objetivo TEXT NOT NULL,
  alineacion_estrategica TEXT, -- Cómo se alinea con la estrategia
  proceso_relacionado TEXT,
  area_responsable TEXT,
  responsable TEXT NOT NULL,
  
  -- Planificación
  fecha_inicio DATE NOT NULL,
  fecha_meta DATE NOT NULL,
  
  -- Medición
  indicador_medicion TEXT NOT NULL,
  frecuencia_medicion TEXT, -- 'mensual', 'trimestral', 'anual'
  
  valor_inicial NUMERIC,
  valor_actual NUMERIC,
  valor_meta NUMERIC,
  unidad_medida TEXT,
  
  -- Seguimiento
  porcentaje_avance NUMERIC,
  estado TEXT DEFAULT 'activo', -- 'activo', 'en_riesgo', 'completado', 'no_cumplido', 'cancelado'
  
  -- Análisis
  fecha_ultima_medicion DATE,
  tendencia TEXT, -- 'favorable', 'estable', 'desfavorable'
  desviaciones TEXT,
  causas_desviacion TEXT,
  acciones_correctivas TEXT,
  
  recursos_asignados TEXT,
  riesgos_identificados TEXT,
  
  observaciones TEXT,
  lecciones_aprendidas TEXT
);

-- 9.3.2.c.3) Desempeño de procesos y conformidad de productos/servicios

-- Visitas de inspección y verificación
CREATE TABLE IF NOT EXISTS inspecciones_verificacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_inspeccion DATE NOT NULL,
  tipo_inspeccion TEXT, -- 'producto', 'proceso', 'instalaciones', 'documentacion'
  
  -- Alcance
  proceso_inspeccionado TEXT,
  area TEXT,
  lote_producto TEXT,
  turno TEXT,
  
  -- Responsables
  inspector TEXT NOT NULL,
  rol_inspector TEXT, -- 'calidad', 'produccion', 'supervisor', 'externo'
  acompanantes TEXT[],
  
  -- Criterios
  criterios_evaluacion TEXT,
  norma_aplicable TEXT, -- ISO 9001, especificaciones técnicas, etc.
  
  -- Resultados
  items_inspeccionados INT,
  items_conformes INT,
  items_no_conformes INT,
  porcentaje_conformidad NUMERIC,
  
  resultado_general TEXT, -- 'conforme', 'conforme_con_observaciones', 'no_conforme'
  
  -- Hallazgos
  hallazgos TEXT,
  observaciones_menor TEXT,
  no_conformidades_detectadas TEXT,
  
  -- Seguimiento
  acciones_inmediatas TEXT,
  requiere_accion_correctiva BOOLEAN DEFAULT false,
  nc_generada_id BIGINT, -- Referencia a no_conformidades
  
  evidencias_fotograficas TEXT[],
  documentos_adjuntos TEXT[],
  
  fecha_seguimiento DATE,
  estado_seguimiento TEXT, -- 'pendiente', 'en_proceso', 'cerrado'
  
  observaciones TEXT
);

-- 9.3.2.c.4) No conformidades y acciones correctivas
-- Ya existe la tabla no_conformidades, vamos a mejorarla

DROP TABLE IF EXISTS no_conformidades CASCADE;

CREATE TABLE no_conformidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Identificación
  codigo_nc TEXT, -- 'NC-2024-001'
  fecha_deteccion DATE NOT NULL,
  fecha_ocurrencia DATE,
  
  origen TEXT, -- 'auditoria_interna', 'auditoria_externa', 'inspeccion', 'cliente', 'proceso'
  origen_id BIGINT, -- ID de la auditoría, inspección o queja que originó la NC
  
  tipo TEXT, -- 'producto', 'proceso', 'sistema', 'servicio'
  severidad TEXT, -- 'critica', 'mayor', 'menor'
  
  -- Descripción
  proceso_afectado TEXT,
  descripcion TEXT NOT NULL,
  evidencia_objetiva TEXT,
  
  -- Análisis
  causa_inmediata TEXT,
  causa_raiz TEXT,
  metodologia_analisis TEXT, -- '5 porqués', 'ishikawa', 'pareto', etc.
  
  -- Acción Correctiva
  accion_contencion TEXT, -- Acción inmediata
  fecha_contencion DATE,
  
  accion_correctiva TEXT,
  plan_accion TEXT,
  recursos_necesarios TEXT,
  
  -- Responsabilidad
  reportado_por TEXT,
  responsable_analisis TEXT,
  responsable_accion TEXT,
  area_responsable TEXT,
  
  -- Plazos
  fecha_compromiso_cierre DATE,
  fecha_cierre DATE,
  
  -- Verificación
  verificacion_eficacia TEXT,
  metodo_verificacion TEXT,
  fecha_verificacion DATE,
  verificado_por TEXT,
  eficacia_verificada BOOLEAN DEFAULT false,
  
  -- Seguimiento
  estado TEXT DEFAULT 'abierta', -- 'abierta', 'en_analisis', 'en_implementacion', 'en_verificacion', 'cerrada', 'reabierta'
  
  -- Recurrencia
  es_recurrente BOOLEAN DEFAULT false,
  nc_relacionadas TEXT[], -- IDs de NCs similares
  frecuencia_ocurrencia INT DEFAULT 1,
  
  costo_estimado NUMERIC,
  
  observaciones TEXT,
  lecciones_aprendidas TEXT
);

-- 9.3.2.c.5) Resultados de seguimiento y medición
-- Ya existe la tabla indicadores (KPIs)

-- 9.3.2.c.6) Resultados de auditorías
-- Ya existe la tabla auditorias

-- 9.3.2.c.7) Desempeño de proveedores externos
-- Ya existe la tabla proveedores, vamos a crear tabla para auditorías a proveedores

CREATE TABLE IF NOT EXISTS auditorias_proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE CASCADE,
  
  fecha_auditoria DATE NOT NULL,
  tipo_auditoria TEXT, -- 'documental', 'in_situ', 'seguimiento', 'especial'
  alcance TEXT,
  
  -- Equipo auditor
  auditor_lider TEXT,
  equipo_auditor TEXT[],
  
  -- Criterios
  normas_evaluadas TEXT[], -- ISO 9001, ISO 14001, etc.
  criterios_especificos TEXT,
  
  -- Resultados
  hallazgos_totales INT DEFAULT 0,
  conformidades INT DEFAULT 0,
  no_conformidades_mayores INT DEFAULT 0,
  no_conformidades_menores INT DEFAULT 0,
  observaciones_count INT DEFAULT 0,
  oportunidades_mejora INT DEFAULT 0,
  
  -- Calificación
  calificacion_auditoria NUMERIC, -- 0-100
  resultado_general TEXT, -- 'satisfactorio', 'aceptable', 'requiere_mejoras', 'no_satisfactorio'
  
  -- Hallazgos críticos
  hallazgos_criticos TEXT,
  
  -- Plan de acción
  acciones_correctivas_solicitadas TEXT,
  fecha_compromiso_proveedor DATE,
  
  -- Seguimiento
  fecha_seguimiento DATE,
  estado_seguimiento TEXT, -- 'pendiente', 'en_proceso', 'cerrado'
  acciones_cerradas INT,
  acciones_pendientes INT,
  
  -- Impacto en calificación
  afecta_calificacion BOOLEAN DEFAULT true,
  
  informe_auditoria_url TEXT,
  evidencias TEXT[],
  
  observaciones TEXT,
  recomendaciones TEXT
);

-- 9.3.2.d) Adecuación de recursos
CREATE TABLE IF NOT EXISTS recursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  tipo_recurso TEXT NOT NULL, -- 'humano', 'infraestructura', 'tecnologico', 'financiero', 'informacion', 'ambiente_trabajo'
  categoria TEXT, -- Subcategoría específica
  
  -- Identificación
  nombre_recurso TEXT NOT NULL,
  codigo_recurso TEXT,
  ubicacion TEXT,
  area_asignada TEXT,
  
  -- Estado actual
  estado_actual TEXT, -- 'disponible', 'insuficiente', 'adecuado', 'requiere_actualizacion', 'obsoleto'
  cantidad_actual TEXT,
  capacidad_disponible NUMERIC,
  capacidad_utilizada NUMERIC,
  porcentaje_uso NUMERIC,
  
  -- Evaluación
  fecha_evaluacion DATE,
  evaluado_por TEXT,
  criterios_evaluacion TEXT,
  cumple_requisitos BOOLEAN,
  
  -- Necesidades identificadas
  necesidad_adicional BOOLEAN DEFAULT false,
  tipo_necesidad TEXT, -- 'incremento_cantidad', 'actualizacion', 'reemplazo', 'mantenimiento', 'capacitacion'
  cantidad_requerida TEXT,
  descripcion_necesidad TEXT,
  justificacion TEXT NOT NULL,
  
  -- Impacto
  impacto_no_disponibilidad TEXT, -- 'critico', 'alto', 'medio', 'bajo'
  procesos_afectados TEXT[],
  
  -- Prioridad y aprobación
  prioridad TEXT, -- 'critica', 'alta', 'media', 'baja'
  urgencia TEXT, -- 'inmediata', 'corto_plazo', 'mediano_plazo', 'largo_plazo'
  
  -- Financiero
  costo_estimado NUMERIC,
  fuente_financiamiento TEXT,
  presupuesto_aprobado BOOLEAN DEFAULT false,
  
  -- Seguimiento
  estado_solicitud TEXT DEFAULT 'identificado', -- 'identificado', 'solicitado', 'aprobado', 'rechazado', 'en_adquisicion', 'implementado'
  fecha_solicitud DATE,
  fecha_aprobacion DATE,
  aprobado_por TEXT,
  
  fecha_implementacion_prevista DATE,
  fecha_implementacion_real DATE,
  
  proveedor_seleccionado TEXT,
  
  observaciones TEXT,
  seguimiento TEXT
);

-- 9.3.2.e) Eficacia de acciones para riesgos y oportunidades
CREATE TABLE IF NOT EXISTS riesgos_oportunidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Identificación
  codigo TEXT, -- 'R-001', 'O-001'
  fecha_identificacion DATE NOT NULL,
  tipo TEXT NOT NULL, -- 'riesgo', 'oportunidad'
  
  -- Clasificación
  categoria TEXT, -- 'estrategico', 'operacional', 'financiero', 'cumplimiento', 'reputacional', 'tecnologico'
  origen TEXT, -- De dónde surge
  
  -- Descripción
  descripcion TEXT NOT NULL,
  causa_origen TEXT,
  proceso_relacionado TEXT,
  contexto TEXT, -- Contexto organizacional relacionado
  
  -- Evaluación de Riesgo/Oportunidad
  probabilidad INT, -- 1-5 (Muy baja a Muy alta)
  impacto INT, -- 1-5 (Muy bajo a Muy alto)
  nivel_riesgo INT, -- probabilidad x impacto (1-25)
  
  clasificacion_nivel TEXT, -- 'bajo', 'medio', 'alto', 'critico'
  
  -- Partes interesadas afectadas
  partes_interesadas TEXT[],
  
  -- Tratamiento/Aprovechamiento
  estrategia TEXT, -- Para riesgo: 'evitar', 'reducir', 'transferir', 'aceptar' | Para oportunidad: 'explotar', 'mejorar', 'compartir'
  
  acciones_planificadas TEXT NOT NULL,
  controles_existentes TEXT,
  controles_adicionales TEXT,
  
  -- Responsabilidad
  responsable TEXT NOT NULL,
  area_responsable TEXT,
  
  -- Recursos
  recursos_necesarios TEXT,
  costo_estimado NUMERIC,
  
  -- Implementación
  fecha_implementacion DATE,
  plazo_implementacion TEXT,
  
  -- Seguimiento y medición
  indicadores_seguimiento TEXT,
  frecuencia_revision TEXT, -- 'mensual', 'trimestral', 'semestral', 'anual', 'continua'
  
  fecha_ultima_revision DATE,
  estado_implementacion TEXT, -- 'identificado', 'planificado', 'en_implementacion', 'implementado', 'en_seguimiento'
  
  -- Eficacia
  fecha_evaluacion_eficacia DATE,
  evaluado_por TEXT,
  eficacia_acciones TEXT, -- 'muy_eficaz', 'eficaz', 'parcialmente_eficaz', 'no_eficaz'
  
  nivel_riesgo_residual INT, -- Después de controles
  
  -- Materialización (para riesgos)
  riesgo_materializado BOOLEAN DEFAULT false,
  fecha_materializacion DATE,
  descripcion_materializacion TEXT,
  impacto_real TEXT,
  acciones_contingencia TEXT,
  
  -- Aprovechamiento (para oportunidades)
  oportunidad_aprovechada BOOLEAN DEFAULT false,
  beneficios_obtenidos TEXT,
  
  estado TEXT DEFAULT 'activo', -- 'activo', 'en_tratamiento', 'controlado', 'cerrado', 'materializado'
  
  evidencias TEXT[],
  observaciones TEXT,
  lecciones_aprendidas TEXT
);

-- 9.3.2.f) Oportunidades de mejora
CREATE TABLE IF NOT EXISTS oportunidades_mejora (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Identificación
  codigo_om TEXT, -- 'OM-2024-001'
  fecha_identificacion DATE NOT NULL,
  
  origen TEXT, -- 'auditoria', 'revision_direccion', 'iniciativa_propia', 'sugerencia_personal', 'cliente', 'benchmarking'
  origen_id BIGINT, -- ID del registro que originó la OM
  
  -- Descripción
  titulo TEXT NOT NULL,
  descripcion_situacion_actual TEXT NOT NULL,
  descripcion_mejora_propuesta TEXT NOT NULL,
  
  -- Análisis
  proceso_afectado TEXT,
  area_responsable TEXT,
  
  beneficios_esperados TEXT,
  impacto_esperado TEXT, -- 'alto', 'medio', 'bajo'
  tipo_beneficio TEXT[], -- 'reduccion_costos', 'mejora_calidad', 'aumento_productividad', 'satisfaccion_cliente', 'cumplimiento_normativo'
  
  -- Viabilidad
  analisis_viabilidad TEXT,
  factibilidad_tecnica TEXT, -- 'alta', 'media', 'baja'
  factibilidad_economica TEXT,
  
  -- Recursos
  recursos_necesarios TEXT,
  costo_estimado NUMERIC,
  retorno_inversion_estimado TEXT,
  
  -- Priorización
  prioridad TEXT, -- 'critica', 'alta', 'media', 'baja'
  urgencia TEXT,
  
  -- Responsabilidad
  propuesta_por TEXT,
  responsable_implementacion TEXT,
  
  -- Planificación
  fecha_aprobacion DATE,
  aprobada_por TEXT,
  
  plan_implementacion TEXT,
  fecha_inicio_prevista DATE,
  fecha_fin_prevista DATE,
  
  -- Implementación
  fecha_inicio_real DATE,
  fecha_fin_real DATE,
  
  estado TEXT DEFAULT 'propuesta', -- 'propuesta', 'en_evaluacion', 'aprobada', 'rechazada', 'en_implementacion', 'implementada', 'cancelada'
  porcentaje_avance NUMERIC DEFAULT 0,
  
  -- Verificación
  fecha_verificacion DATE,
  verificada_por TEXT,
  resultados_obtenidos TEXT,
  beneficios_reales TEXT,
  
  eficaz BOOLEAN,
  requiere_estandarizacion BOOLEAN,
  documentacion_actualizada BOOLEAN,
  
  observaciones TEXT,
  lecciones_aprendidas TEXT
);

-- ============================================
-- REVISIONES POR LA DIRECCIÓN
-- ============================================

DROP TABLE IF EXISTS revisiones CASCADE;

CREATE TABLE revisiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Información General
  codigo_revision TEXT, -- 'RD-2024-Q4'
  titulo TEXT NOT NULL,
  fecha_revision DATE NOT NULL,
  hora_inicio TIME,
  hora_fin TIME,
  lugar TEXT,
  
  responsable TEXT NOT NULL,
  cargo_responsable TEXT,
  participantes TEXT[],
  invitados_especiales TEXT[],
  
  estado TEXT DEFAULT 'planificada', -- 'planificada', 'en_curso', 'finalizada', 'en_seguimiento', 'cerrada'
  
  -- === ENTRADAS (9.3.2) ===
  
  -- a) Estado de acciones de revisiones previas
  revision_previa_id BIGINT, -- ID de la revisión anterior
  analisis_compromisos_previos TEXT,
  porcentaje_cumplimiento_previo NUMERIC,
  compromisos_pendientes_analisis TEXT,
  
  -- b) Cambios en cuestiones externas e internas
  analisis_cambios_externos TEXT,
  analisis_cambios_internos TEXT,
  sintesis_gestion_cambios TEXT,
  
  -- c) Información sobre desempeño y eficacia del SGC
  
  -- c.1) Satisfacción del cliente y retroalimentación
  analisis_satisfaccion_cliente TEXT,
  analisis_pqrs TEXT,
  analisis_partes_interesadas TEXT,
  sintesis_voz_cliente TEXT,
  
  -- c.2) Grado de logro de objetivos de calidad
  analisis_objetivos_calidad TEXT,
  porcentaje_cumplimiento_objetivos NUMERIC,
  objetivos_criticos_analisis TEXT,
  
  -- c.3) Desempeño de procesos y conformidad
  analisis_inspecciones TEXT,
  analisis_conformidad_productos TEXT,
  analisis_desempeno_procesos TEXT,
  
  -- c.4) No conformidades y acciones correctivas
  analisis_no_conformidades TEXT,
  analisis_recurrencias TEXT,
  eficacia_acciones_correctivas TEXT,
  
  -- c.5) Resultados de seguimiento y medición (KPIs)
  analisis_indicadores TEXT,
  kpis_criticos_analisis TEXT,
  tendencias_identificadas TEXT,
  
  -- c.6) Resultados de auditorías
  analisis_auditorias TEXT,
  analisis_hallazgos_auditoria TEXT,
  estado_acciones_auditoria TEXT,
  
  -- c.7) Desempeño de proveedores externos
  analisis_proveedores TEXT,
  proveedores_criticos_analisis TEXT,
  acciones_proveedores_pendientes TEXT,
  
  -- d) Adecuación de recursos
  analisis_recursos TEXT,
  necesidades_criticas_recursos TEXT,
  analisis_brechas_recursos TEXT,
  
  -- e) Eficacia de acciones para riesgos y oportunidades
  analisis_riesgos TEXT,
  riesgos_materializados_analisis TEXT,
  analisis_oportunidades TEXT,
  oportunidades_aprovechadas_analisis TEXT,
  eficacia_gestion_riesgos TEXT,
  
  -- f) Oportunidades de mejora
  analisis_mejoras TEXT,
  mejoras_implementadas_periodo TEXT,
  nuevas_mejoras_identificadas TEXT,
  
  -- === SALIDAS (9.3.3) ===
  
  -- a) Oportunidades de mejora (SALIDA)
  decisiones_mejora TEXT,
  sintesis_mejoras_acordadas TEXT,
  
  -- b) Cambios en el SGC
  decisiones_cambios_sgc TEXT,
  cambios_politica BOOLEAN DEFAULT false,
  cambios_objetivos BOOLEAN DEFAULT false,
  cambios_procesos BOOLEAN DEFAULT false,
  cambios_documentacion BOOLEAN DEFAULT false,
  sintesis_cambios_sgc TEXT,
  
  -- c) Necesidades de recursos
  decisiones_recursos TEXT,
  sintesis_recursos_aprobados TEXT,
  
  -- Conclusiones generales
  conclusiones_generales TEXT NOT NULL,
  fortalezas_identificadas TEXT,
  debilidades_identificadas TEXT,
  conveniencia_sgc TEXT, -- ¿El SGC es conveniente?
  adecuacion_sgc TEXT, -- ¿El SGC es adecuado?
  eficacia_sgc TEXT, -- ¿El SGC es eficaz?
  alineacion_estrategica TEXT, -- ¿Está alineado con la dirección estratégica?
  
  -- Decisiones estratégicas
  decisiones_estrategicas TEXT,
  
  -- Seguimiento
  fecha_proxima_revision DATE,
  temas_proxima_revision TEXT,
  
  -- Compromisos generados
  total_compromisos INT DEFAULT 0,
  compromisos_mejora INT DEFAULT 0,
  compromisos_cambios_sgc INT DEFAULT 0,
  compromisos_recursos INT DEFAULT 0,
  
  -- Evidencias
  acta_revision_url TEXT,
  presentaciones_url TEXT[],
  evidencias_url TEXT[],
  
  -- Metadata
  porcentaje_cumplimiento NUMERIC DEFAULT 0,
  carpeta_drive TEXT,
  carpeta_onedrive TEXT,
  
  observaciones TEXT,
  elaborado_por TEXT,
  revisado_por TEXT,
  aprobado_por TEXT
);

-- ============================================
-- COMPROMISOS Y SEGUIMIENTO
-- ============================================

DROP TABLE IF EXISTS compromisos CASCADE;

CREATE TABLE compromisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id BIGINT REFERENCES revisiones(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Identificación
  codigo_compromiso TEXT, -- 'C-RD-2024-Q4-001'
  
  -- Clasificación (según salida de revisión)
  tipo_salida TEXT NOT NULL, -- 'mejora', 'cambio_sgc', 'recursos'
  categoria_especifica TEXT, -- Subcategoría más específica
  
  -- Descripción
  descripcion TEXT NOT NULL,
  objetivo TEXT,
  alcance TEXT,
  
  -- Relación con análisis de entradas
  relacionado_con TEXT, -- 'auditorias', 'nc', 'objetivos', 'riesgos', 'proveedores', etc.
  origen_entrada TEXT, -- Descripción de qué entrada generó este compromiso
  
  -- Responsabilidad
  responsable TEXT NOT NULL,
  cargo_responsable TEXT,
  area_responsable TEXT,
  equipo_trabajo TEXT[],
  
  -- Planificación
  plan_accion TEXT,
  actividades TEXT[], -- Lista de actividades a realizar
  hitos TEXT[], -- Hitos importantes
  
  -- Plazos
  fecha_compromiso DATE NOT NULL,
  fecha_limite DATE NOT NULL,
  fecha_cumplimiento DATE,
  
  -- Recursos
  recursos_necesarios TEXT,
  recursos_humanos TEXT,
  recursos_tecnicos TEXT,
  recursos_financieros TEXT,
  presupuesto_estimado NUMERIC,
  presupuesto_aprobado NUMERIC,
  
  -- Estado y seguimiento
  estado TEXT DEFAULT 'pendiente', -- 'pendiente', 'en_proceso', 'en_pausa', 'completado', 'vencido', 'cancelado'
  prioridad TEXT NOT NULL, -- 'critica', 'alta', 'media', 'baja'
  
  -- Avance
  porcentaje_avance NUMERIC DEFAULT 0,
  fecha_ultimo_seguimiento DATE,
  reporte_avance TEXT,
  
  -- Obstáculos y riesgos
  obstaculos_identificados TEXT,
  riesgos_cumplimiento TEXT,
  acciones_mitigacion TEXT,
  
  -- Verificación y cierre
  criterios_aceptacion TEXT,
  evidencias TEXT[],
  
  verificado_por TEXT,
  fecha_verificacion DATE,
  resultado_verificacion TEXT,
  eficaz BOOLEAN,
  
  -- Impacto y beneficios
  beneficios_esperados TEXT,
  beneficios_obtenidos TEXT,
  impacto_sgc TEXT,
  
  -- Extensiones
  requiere_extension BOOLEAN DEFAULT false,
  justificacion_extension TEXT,
  nueva_fecha_limite DATE,
  aprobado_extension_por TEXT,
  
  -- Cierre
  fecha_cierre_real DATE,
  lecciones_aprendidas TEXT,
  
  observaciones TEXT,
  seguimiento_detallado TEXT
);

-- ============================================
-- EVIDENCIAS
-- ============================================

DROP TABLE IF EXISTS evidencias CASCADE;

CREATE TABLE evidencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Vinculación
  revision_id BIGINT REFERENCES revisiones(id) ON DELETE CASCADE,
  compromiso_id BIGINT REFERENCES compromisos(id) ON DELETE CASCADE,
  modulo_origen TEXT, -- 'auditoria', 'nc', 'encuesta', etc.
  registro_origen_id BIGINT,
  
  -- Archivo
  nombre_archivo TEXT NOT NULL,
  tipo_archivo TEXT,
  tamano_bytes BIGINT,
  
  -- Almacenamiento
  url_drive TEXT,
  url_onedrive TEXT,
  url_local TEXT,
  
  -- Clasificación
  categoria TEXT NOT NULL, -- 'entrada', 'analisis', 'salida', 'acta', 'presentacion', 'evidencia_compromiso', 'soporte', 'otro'
  tipo_documento TEXT, -- 'informe', 'registro', 'acta', 'presentacion', 'fotografia', 'video', 'certificado', 'otro'
  
  descripcion TEXT,
  fecha_documento DATE,
  
  -- Control
  version TEXT DEFAULT '1.0',
  confidencial BOOLEAN DEFAULT false,
  
  subido_por TEXT,
  aprobado_por TEXT,
  fecha_aprobacion DATE,
  
  observaciones TEXT
);

-- ============================================
-- RLS Y TRIGGERS
-- ============================================

-- Habilitar RLS en todas las tablas
ALTER TABLE gestion_cambios ENABLE ROW LEVEL SECURITY;
ALTER TABLE encuestas_satisfaccion ENABLE ROW LEVEL SECURITY;
ALTER TABLE objetivos_calidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspecciones_verificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE no_conformidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditorias_proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE recursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE riesgos_oportunidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE oportunidades_mejora ENABLE ROW LEVEL SECURITY;
ALTER TABLE revisiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE compromisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidencias ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso total (temporal para desarrollo)
CREATE POLICY "Acceso total" ON gestion_cambios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON encuestas_satisfaccion FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON objetivos_calidad FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON inspecciones_verificacion FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON no_conformidades FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON auditorias_proveedores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON recursos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON riesgos_oportunidades FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON oportunidades_mejora FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON revisiones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON compromisos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON evidencias FOR ALL USING (true) WITH CHECK (true);

-- Triggers para updated_at
CREATE TRIGGER update_gestion_cambios_updated_at BEFORE UPDATE ON gestion_cambios FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_encuestas_updated_at BEFORE UPDATE ON encuestas_satisfaccion FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_objetivos_updated_at BEFORE UPDATE ON objetivos_calidad FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_inspecciones_updated_at BEFORE UPDATE ON inspecciones_verificacion FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_nc_updated_at BEFORE UPDATE ON no_conformidades FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_audit_prov_updated_at BEFORE UPDATE ON auditorias_proveedores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_recursos_updated_at BEFORE UPDATE ON recursos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_riesgos_updated_at BEFORE UPDATE ON riesgos_oportunidades FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_om_updated_at BEFORE UPDATE ON oportunidades_mejora FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_revisiones_updated_at BEFORE UPDATE ON revisiones FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_compromisos_updated_at BEFORE UPDATE ON compromisos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- FUNCIONES ÚTILES
-- ============================================

-- Calcular cumplimiento de compromisos de una revisión
CREATE OR REPLACE FUNCTION calcular_cumplimiento_revision(revision_id_param BIGINT)
RETURNS NUMERIC AS $$
DECLARE
    total_compromisos INT;
    compromisos_completados INT;
    porcentaje NUMERIC;
BEGIN
    SELECT COUNT(*) INTO total_compromisos 
    FROM compromisos 
    WHERE revision_id = revision_id_param;
    
    IF total_compromisos = 0 THEN
        RETURN 100;
    END IF;
    
    SELECT COUNT(*) INTO compromisos_completados 
    FROM compromisos 
    WHERE revision_id = revision_id_param AND estado = 'completado';
    
    porcentaje := (compromisos_completados::NUMERIC / total_compromisos::NUMERIC) * 100;
    
    RETURN ROUND(porcentaje, 2);
END;
$$ LANGUAGE plpgsql;

-- Actualizar compromisos vencidos
CREATE OR REPLACE FUNCTION actualizar_compromisos_vencidos()
RETURNS void AS $$
BEGIN
    UPDATE compromisos
    SET estado = 'vencido'
    WHERE fecha_limite < CURRENT_DATE
    AND estado IN ('pendiente', 'en_proceso');
END;
$$ LANGUAGE plpgsql;

-- Calcular porcentaje de conformidad general
CREATE OR REPLACE FUNCTION calcular_conformidad_general()
RETURNS NUMERIC AS $$
DECLARE
    total_items INT;
    items_conformes INT;
    porcentaje NUMERIC;
BEGIN
    SELECT 
        SUM(items_inspeccionados),
        SUM(items_conformes)
    INTO total_items, items_conformes
    FROM inspecciones_verificacion
    WHERE fecha_inspeccion >= CURRENT_DATE - INTERVAL '3 months';
    
    IF total_items = 0 THEN
        RETURN 100;
    END IF;
    
    porcentaje := (items_conformes::NUMERIC / total_items::NUMERIC) * 100;
    
    RETURN ROUND(porcentaje, 2);
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- ============================================

-- Gestion Cambios
CREATE INDEX idx_cambios_tipo ON gestion_cambios(tipo_cambio);
CREATE INDEX idx_cambios_estado ON gestion_cambios(estado);
CREATE INDEX idx_cambios_fecha ON gestion_cambios(fecha_identificacion);

-- Encuestas
CREATE INDEX idx_encuestas_periodo ON encuestas_satisfaccion(periodo);
CREATE INDEX idx_encuestas_cliente ON encuestas_satisfaccion(cliente);

-- Objetivos
CREATE INDEX idx_objetivos_periodo ON objetivos_calidad(periodo);
CREATE INDEX idx_objetivos_estado ON objetivos_calidad(estado);
CREATE INDEX idx_objetivos_responsable ON objetivos_calidad(responsable);

-- Inspecciones
CREATE INDEX idx_inspecciones_fecha ON inspecciones_verificacion(fecha_inspeccion);
CREATE INDEX idx_inspecciones_tipo ON inspecciones_verificacion(tipo_inspeccion);
CREATE INDEX idx_inspecciones_resultado ON inspecciones_verificacion(resultado_general);

-- No Conformidades
CREATE INDEX idx_nc_codigo ON no_conformidades(codigo_nc);
CREATE INDEX idx_nc_estado ON no_conformidades(estado);
CREATE INDEX idx_nc_severidad ON no_conformidades(severidad);
CREATE INDEX idx_nc_origen ON no_conformidades(origen);
CREATE INDEX idx_nc_recurrente ON no_conformidades(es_recurrente);

-- Auditorías Proveedores
CREATE INDEX idx_audit_prov_proveedor ON auditorias_proveedores(proveedor_id);
CREATE INDEX idx_audit_prov_fecha ON auditorias_proveedores(fecha_auditoria);

-- Recursos
CREATE INDEX idx_recursos_tipo ON recursos(tipo_recurso);
CREATE INDEX idx_recursos_estado_solicitud ON recursos(estado_solicitud);
CREATE INDEX idx_recursos_prioridad ON recursos(prioridad);

-- Riesgos y Oportunidades
CREATE INDEX idx_riesgos_tipo ON riesgos_oportunidades(tipo);
CREATE INDEX idx_riesgos_nivel ON riesgos_oportunidades(nivel_riesgo);
CREATE INDEX idx_riesgos_estado ON riesgos_oportunidades(estado);

-- Oportunidades de Mejora
CREATE INDEX idx_om_codigo ON oportunidades_mejora(codigo_om);
CREATE INDEX idx_om_estado ON oportunidades_mejora(estado);
CREATE INDEX idx_om_origen ON oportunidades_mejora(origen);

-- Revisiones
CREATE INDEX idx_revisiones_codigo ON revisiones(codigo_revision);
CREATE INDEX idx_revisiones_fecha ON revisiones(fecha_revision);
CREATE INDEX idx_revisiones_estado ON revisiones(estado);

-- Compromisos
CREATE INDEX idx_compromisos_revision ON compromisos(revision_id);
CREATE INDEX idx_compromisos_codigo ON compromisos(codigo_compromiso);
CREATE INDEX idx_compromisos_tipo ON compromisos(tipo_salida);
CREATE INDEX idx_compromisos_estado ON compromisos(estado);
CREATE INDEX idx_compromisos_responsable ON compromisos(responsable);
CREATE INDEX idx_compromisos_prioridad ON compromisos(prioridad);

-- Evidencias
CREATE INDEX idx_evidencias_revision ON evidencias(revision_id);
CREATE INDEX idx_evidencias_compromiso ON evidencias(compromiso_id);
CREATE INDEX idx_evidencias_categoria ON evidencias(categoria);
