-- ============================================
-- SISTEMA DE GESTIÓN DE CALIDAD ISO 9001:2015
-- Schema completo para cláusula 9.3 - Revisión por la Dirección
-- ============================================

-- ============================================
-- MÓDULOS OPERATIVOS (ENTRADAS)
-- ============================================

-- 1. OBJETIVOS DE CALIDAD (9.3.2.c.2)
CREATE TABLE IF NOT EXISTS objetivos_calidad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  periodo TEXT NOT NULL, -- 'Q1-2024', '2024', etc.
  objetivo TEXT NOT NULL,
  area_responsable TEXT,
  responsable TEXT,
  fecha_inicio DATE,
  fecha_meta DATE,
  estado TEXT DEFAULT 'activo', -- 'activo', 'completado', 'cancelado', 'retrasado'
  
  -- Métricas
  indicador_medicion TEXT,
  valor_inicial NUMERIC,
  valor_actual NUMERIC,
  valor_meta NUMERIC,
  unidad_medida TEXT,
  porcentaje_avance NUMERIC,
  
  -- Seguimiento
  ultimo_seguimiento DATE,
  observaciones TEXT,
  riesgos_identificados TEXT,
  acciones_mitigacion TEXT
);

-- 2. CONTEXTO ORGANIZACIONAL (9.3.2.b)
CREATE TABLE IF NOT EXISTS contexto_organizacional (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_registro DATE NOT NULL,
  tipo TEXT, -- 'externo', 'interno'
  categoria TEXT, -- 'economico', 'legal', 'tecnologico', 'competitivo', 'social', 'organizacional', 'operacional'
  
  descripcion TEXT NOT NULL,
  impacto_sgc TEXT, -- 'alto', 'medio', 'bajo'
  oportunidad_amenaza TEXT, -- 'oportunidad', 'amenaza', 'neutral'
  
  -- Análisis
  partes_interesadas_afectadas TEXT[],
  procesos_impactados TEXT[],
  acciones_tomadas TEXT,
  responsable TEXT,
  estado TEXT DEFAULT 'activo' -- 'activo', 'mitigado', 'cerrado'
);

-- 3. RIESGOS Y OPORTUNIDADES (9.3.2.e)
CREATE TABLE IF NOT EXISTS riesgos_oportunidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_identificacion DATE NOT NULL,
  tipo TEXT, -- 'riesgo', 'oportunidad'
  categoria TEXT, -- 'operacional', 'estrategico', 'financiero', 'cumplimiento', 'reputacional'
  
  descripcion TEXT NOT NULL,
  proceso_relacionado TEXT,
  
  -- Evaluación de Riesgo
  probabilidad INT, -- 1-5
  impacto INT, -- 1-5
  nivel_riesgo INT, -- probabilidad x impacto (1-25)
  
  -- Plan de Acción
  acciones_planificadas TEXT,
  responsable TEXT,
  fecha_implementacion DATE,
  
  -- Seguimiento
  estado TEXT DEFAULT 'identificado', -- 'identificado', 'en_tratamiento', 'mitigado', 'cerrado'
  eficacia_acciones TEXT,
  fecha_revision DATE,
  observaciones TEXT
);

-- 4. RECURSOS (9.3.2.d y 9.3.3.c)
CREATE TABLE IF NOT EXISTS recursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  tipo_recurso TEXT, -- 'humano', 'infraestructura', 'tecnologico', 'financiero', 'informacion'
  nombre_recurso TEXT NOT NULL,
  area TEXT,
  
  -- Estado actual
  estado_actual TEXT, -- 'disponible', 'insuficiente', 'adecuado', 'requiere_mejora'
  cantidad_actual TEXT,
  capacidad_utilizada NUMERIC, -- porcentaje
  
  -- Necesidades
  necesidad_adicional BOOLEAN DEFAULT false,
  cantidad_requerida TEXT,
  justificacion TEXT,
  prioridad TEXT, -- 'alta', 'media', 'baja'
  
  -- Seguimiento
  fecha_evaluacion DATE,
  responsable TEXT,
  costo_estimado NUMERIC,
  estado_solicitud TEXT, -- 'pendiente', 'aprobado', 'rechazado', 'en_proceso'
  observaciones TEXT
);

-- 5. SEGUIMIENTO Y MEDICIÓN (9.3.2.c.5)
CREATE TABLE IF NOT EXISTS seguimiento_medicion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_medicion DATE NOT NULL,
  tipo_medicion TEXT, -- 'producto', 'proceso', 'satisfaccion_cliente', 'sistema'
  nombre_medicion TEXT NOT NULL,
  metodo_medicion TEXT,
  
  -- Resultados
  resultado_obtenido TEXT,
  valor_numerico NUMERIC,
  unidad_medida TEXT,
  cumple_criterio BOOLEAN,
  
  -- Análisis
  desviaciones_encontradas TEXT,
  causas_analisis TEXT,
  acciones_tomadas TEXT,
  
  responsable TEXT,
  proceso_relacionado TEXT,
  observaciones TEXT
);

-- 6. DESEMPEÑO DE PROCESOS Y CONFORMIDAD (9.3.2.c.3)
CREATE TABLE IF NOT EXISTS desempeno_procesos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  periodo TEXT NOT NULL,
  nombre_proceso TEXT NOT NULL,
  responsable_proceso TEXT,
  
  -- Desempeño
  eficacia NUMERIC, -- %
  eficiencia NUMERIC, -- %
  productos_conformes INT,
  productos_no_conformes INT,
  porcentaje_conformidad NUMERIC,
  
  -- Capacidad
  tiempo_ciclo_promedio NUMERIC,
  unidad_tiempo TEXT,
  capacidad_instalada NUMERIC,
  capacidad_utilizada NUMERIC,
  
  -- Análisis
  tendencia TEXT, -- 'mejora', 'estable', 'deterioro'
  problemas_identificados TEXT,
  mejoras_implementadas TEXT,
  objetivos_cumplidos BOOLEAN,
  observaciones TEXT
);

-- 7. PARTES INTERESADAS
CREATE TABLE IF NOT EXISTS partes_interesadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  nombre TEXT NOT NULL,
  tipo TEXT, -- 'cliente', 'proveedor', 'empleado', 'regulador', 'accionista', 'comunidad'
  
  -- Necesidades y Expectativas
  necesidades_expectativas TEXT,
  requisitos_aplicables TEXT,
  
  -- Comunicación
  metodo_comunicacion TEXT,
  frecuencia_comunicacion TEXT,
  ultimo_contacto DATE,
  nivel_satisfaccion INT, -- 1-5
  
  -- Impacto
  nivel_influencia TEXT, -- 'alto', 'medio', 'bajo'
  nivel_interes TEXT, -- 'alto', 'medio', 'bajo'
  
  responsable_relacion TEXT,
  observaciones TEXT
);

-- ============================================
-- TABLAS EXISTENTES (Ya creadas anteriormente)
-- ============================================

-- auditorias
-- quejas_reclamos
-- indicadores
-- no_conformidades
-- proveedores

-- ============================================
-- REVISIONES Y COMPROMISOS
-- ============================================

-- TABLA PRINCIPAL: REVISIONES
CREATE TABLE IF NOT EXISTS revisiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Información General
  titulo TEXT NOT NULL,
  fecha_revision DATE NOT NULL,
  responsable TEXT NOT NULL,
  participantes TEXT[],
  estado TEXT DEFAULT 'abierta', -- 'abierta', 'en_seguimiento', 'cerrada'
  
  -- ENTRADAS: Análisis de la Alta Dirección
  -- a) Estado de acciones previas
  analisis_acciones_previas TEXT,
  
  -- b) Cambios externos e internos
  analisis_cambios_externos TEXT,
  analisis_cambios_internos TEXT,
  
  -- c) Información sobre desempeño y eficacia
  -- c.1) Satisfacción del cliente
  analisis_clientes TEXT,
  
  -- c.2) Logro de objetivos de calidad
  analisis_objetivos TEXT,
  
  -- c.3) Desempeño de procesos y conformidad
  analisis_procesos TEXT,
  
  -- c.4) No conformidades y acciones correctivas
  analisis_no_conformidades TEXT,
  
  -- c.5) Resultados de seguimiento y medición
  analisis_seguimiento_medicion TEXT,
  
  -- c.6) Resultados de auditorías
  analisis_auditorias TEXT,
  
  -- c.7) Desempeño de proveedores externos
  analisis_proveedores TEXT,
  
  -- d) Adecuación de recursos
  analisis_recursos TEXT,
  
  -- e) Eficacia de acciones para riesgos y oportunidades
  analisis_riesgos TEXT,
  analisis_oportunidades TEXT,
  
  -- f) Oportunidades de mejora
  oportunidades_mejora_identificadas TEXT,
  
  -- SALIDAS: Decisiones (9.3.3)
  -- a) Oportunidades de mejora
  decisiones_mejora TEXT,
  
  -- b) Cambios en el SGC
  decisiones_sgc TEXT,
  
  -- c) Necesidades de recursos
  necesidades_recursos TEXT,
  
  -- Conclusiones generales
  conclusiones_generales TEXT,
  
  -- Metadata
  porcentaje_cumplimiento NUMERIC DEFAULT 0,
  carpeta_drive TEXT,
  carpeta_onedrive TEXT
);

-- TABLA: COMPROMISOS
CREATE TABLE IF NOT EXISTS compromisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id BIGINT REFERENCES revisiones(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Información del compromiso
  tipo_salida TEXT, -- 'mejora', 'cambio_sgc', 'recursos'
  descripcion TEXT NOT NULL,
  objetivo TEXT,
  
  -- Responsabilidad
  responsable TEXT NOT NULL,
  area_responsable TEXT,
  
  -- Plazos
  fecha_compromiso DATE NOT NULL,
  fecha_limite DATE NOT NULL,
  fecha_cumplimiento DATE,
  
  -- Estado y seguimiento
  estado TEXT DEFAULT 'pendiente', -- 'pendiente', 'en_proceso', 'completado', 'vencido', 'cancelado'
  prioridad TEXT, -- 'alta', 'media', 'baja'
  porcentaje_avance NUMERIC DEFAULT 0,
  
  -- Recursos
  recursos_necesarios TEXT,
  presupuesto_estimado NUMERIC,
  
  -- Evidencias
  evidencias TEXT[],
  observaciones TEXT,
  
  -- Verificación
  verificado_por TEXT,
  fecha_verificacion DATE,
  eficaz BOOLEAN
);

-- TABLA: EVIDENCIAS
CREATE TABLE IF NOT EXISTS evidencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id BIGINT REFERENCES revisiones(id) ON DELETE CASCADE,
  compromiso_id BIGINT REFERENCES compromisos(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  nombre_archivo TEXT NOT NULL,
  tipo_archivo TEXT,
  url_drive TEXT,
  url_onedrive TEXT,
  categoria TEXT, -- 'entrada', 'salida', 'acta', 'presentacion', 'evidencia_compromiso', 'otro'
  descripcion TEXT,
  subido_por TEXT,
  fecha_subida TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- POLÍTICAS DE SEGURIDAD (RLS)
-- ============================================

ALTER TABLE objetivos_calidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE contexto_organizacional ENABLE ROW LEVEL SECURITY;
ALTER TABLE riesgos_oportunidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE recursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE seguimiento_medicion ENABLE ROW LEVEL SECURITY;
ALTER TABLE desempeno_procesos ENABLE ROW LEVEL SECURITY;
ALTER TABLE partes_interesadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE revisiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE compromisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidencias ENABLE ROW LEVEL SECURITY;

-- Políticas temporales para desarrollo
CREATE POLICY "Acceso total" ON objetivos_calidad FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON contexto_organizacional FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON riesgos_oportunidades FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON recursos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON seguimiento_medicion FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON desempeno_procesos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON partes_interesadas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON revisiones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON compromisos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso total" ON evidencias FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- TRIGGERS Y FUNCIONES
-- ============================================

-- Trigger para updated_at
CREATE TRIGGER update_objetivos_updated_at BEFORE UPDATE ON objetivos_calidad
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_contexto_updated_at BEFORE UPDATE ON contexto_organizacional
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_riesgos_updated_at BEFORE UPDATE ON riesgos_oportunidades
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_recursos_updated_at BEFORE UPDATE ON recursos
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_seguimiento_updated_at BEFORE UPDATE ON seguimiento_medicion
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_procesos_updated_at BEFORE UPDATE ON desempeno_procesos
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_partes_updated_at BEFORE UPDATE ON partes_interesadas
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_revisiones_updated_at BEFORE UPDATE ON revisiones
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_compromisos_updated_at BEFORE UPDATE ON compromisos
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Función para calcular cumplimiento de revisión
CREATE OR REPLACE FUNCTION calcular_cumplimiento_revision(revision_id_param BIGINT)
RETURNS NUMERIC AS $$
DECLARE
    total_compromisos INT;
    compromisos_completados INT;
    porcentaje NUMERIC;
BEGIN
    SELECT COUNT(*) INTO total_compromisos 
    FROM compromisos 
    WHERE revision_id = revision_id_param;
    
    IF total_compromisos = 0 THEN
        RETURN 100; -- Si no hay compromisos, consideramos 100%
    END IF;
    
    SELECT COUNT(*) INTO compromisos_completados 
    FROM compromisos 
    WHERE revision_id = revision_id_param AND estado = 'completado';
    
    porcentaje := (compromisos_completados::NUMERIC / total_compromisos::NUMERIC) * 100;
    
    RETURN ROUND(porcentaje, 2);
END;
$$ LANGUAGE plpgsql;

-- Función para actualizar estado de compromisos vencidos
CREATE OR REPLACE FUNCTION actualizar_compromisos_vencidos()
RETURNS void AS $$
BEGIN
    UPDATE compromisos
    SET estado = 'vencido'
    WHERE fecha_limite < CURRENT_DATE
    AND estado IN ('pendiente', 'en_proceso');
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- DATOS DE DEMOSTRACIÓN
-- ============================================

-- OBJETIVOS DE CALIDAD
INSERT INTO objetivos_calidad (periodo, objetivo, area_responsable, responsable, fecha_inicio, fecha_meta, estado, indicador_medicion, valor_inicial, valor_actual, valor_meta, unidad_medida, porcentaje_avance, ultimo_seguimiento, observaciones) VALUES
('2024', 'Reducir productos no conformes', 'Calidad', 'Jefe de Calidad', '2024-01-01', '2024-12-31', 'activo', 'Porcentaje de productos no conformes', 4.5, 2.1, 2.0, '%', 85, '2024-11-30', 'En buen avance. Implementación de controles adicionales.'),
('2024', 'Aumentar satisfacción del cliente', 'Comercial', 'Director Comercial', '2024-01-01', '2024-12-31', 'activo', 'Índice de satisfacción', 85.0, 92.5, 90.0, '%', 100, '2024-11-30', 'Meta superada. Excelente resultado.'),
('2024', 'Mejorar eficiencia de producción', 'Producción', 'Gerente de Producción', '2024-01-01', '2024-12-31', 'activo', 'Eficiencia global', 82.0, 87.0, 88.0, '%', 71, '2024-11-30', 'Avance satisfactorio. Requiere aceleración en Q1-2025.'),
('Q4-2024', 'Certificar a 100% del personal en nuevos procedimientos', 'RRHH', 'Director RRHH', '2024-10-01', '2024-12-31', 'activo', 'Porcentaje de personal certificado', 65.0, 89.0, 100.0, '%', 69, '2024-12-01', 'En proceso. Capacitaciones programadas para diciembre.'),
('2024', 'Reducir tiempo de respuesta a quejas', 'Servicio al Cliente', 'Jefe de Servicio', '2024-01-01', '2024-12-31', 'completado', 'Tiempo promedio de respuesta', 5.0, 2.5, 3.0, 'días', 100, '2024-11-30', 'Objetivo cumplido exitosamente.');

-- CONTEXTO ORGANIZACIONAL
INSERT INTO contexto_organizacional (fecha_registro, tipo, categoria, descripcion, impacto_sgc, oportunidad_amenaza, partes_interesadas_afectadas, procesos_impactados, acciones_tomadas, responsable, estado) VALUES
('2024-09-15', 'externo', 'legal', 'Nueva normativa ambiental ISO 14001 exigida por principales clientes', 'alto', 'oportunidad', ARRAY['Clientes', 'Reguladores'], ARRAY['Gestión ambiental', 'Producción'], 'Iniciado proyecto de certificación ISO 14001. Auditoría diagnóstico completada.', 'Gerente General', 'activo'),
('2024-10-01', 'externo', 'economico', 'Aumento de costos de materias primas (15% promedio)', 'medio', 'amenaza', ARRAY['Proveedores', 'Accionistas'], ARRAY['Compras', 'Finanzas'], 'Negociación con proveedores. Análisis de proveedores alternativos.', 'Gerente de Compras', 'activo'),
('2024-08-20', 'interno', 'tecnologico', 'Implementación de ERP integrado', 'alto', 'oportunidad', ARRAY['Empleados', 'Gerencia'], ARRAY['Todos los procesos'], 'Sistema en fase de migración. Capacitación del 70% del personal completada.', 'Director TI', 'activo'),
('2024-11-10', 'externo', 'competitivo', 'Entrada de nuevo competidor con precios 20% menores', 'alto', 'amenaza', ARRAY['Clientes', 'Accionistas'], ARRAY['Ventas', 'Marketing'], 'Plan de fidelización de clientes. Análisis de optimización de costos.', 'Director Comercial', 'activo'),
('2024-07-01', 'interno', 'organizacional', 'Reestructuración del área de calidad', 'medio', 'oportunidad', ARRAY['Empleados'], ARRAY['Gestión de calidad'], 'Nueva estructura implementada. Dos nuevas posiciones creadas.', 'Gerente General', 'mitigado');

-- RIESGOS Y OPORTUNIDADES
INSERT INTO riesgos_oportunidades (fecha_identificacion, tipo, categoria, descripcion, proceso_relacionado, probabilidad, impacto, nivel_riesgo, acciones_planificadas, responsable, fecha_implementacion, estado, eficacia_acciones, observaciones) VALUES
('2024-06-15', 'riesgo', 'operacional', 'Dependencia de único proveedor crítico de materia prima A', 'Compras', 4, 5, 20, 'Calificación de 2 proveedores alternativos. Establecimiento de stock de seguridad.', 'Gerente de Compras', '2024-09-01', 'en_tratamiento', 'Eficaz - Stock de seguridad establecido. Proveedor alternativo en evaluación.', 'Riesgo crítico en seguimiento continuo.'),
('2024-08-01', 'oportunidad', 'estrategico', 'Expansión a mercado de exportación (Colombia)', 'Ventas', 3, 4, 12, 'Estudio de mercado completado. Trámites de exportación iniciados.', 'Director Comercial', '2025-01-01', 'en_tratamiento', 'En desarrollo - Primera exportación programada Q1-2025.', 'Oportunidad de alto potencial.'),
('2024-09-20', 'riesgo', 'cumplimiento', 'Posible auditoría de ente regulador sin anuncio previo', 'Sistema de Gestión', 3, 4, 12, 'Auditoría interna preventiva. Actualización de documentación. Capacitación de personal.', 'Representante de Calidad', '2024-10-15', 'mitigado', 'Muy eficaz - Sistema auditado internamente. No conformidades cerradas.', 'Riesgo reducido a nivel bajo.'),
('2024-10-05', 'riesgo', 'operacional', 'Falta de personal calificado en área técnica', 'Producción', 4, 3, 12, 'Programa de capacitación interna. Alianza con instituto técnico. Plan de retención.', 'Director RRHH', '2024-11-01', 'en_tratamiento', 'Parcialmente eficaz - 5 técnicos en capacitación.', 'Requiere seguimiento trimestral.'),
('2024-11-01', 'oportunidad', 'tecnologico', 'Automatización de línea de producción 2', 'Producción', 2, 5, 10, 'Estudio de viabilidad. Cotización de equipos. ROI proyectado: 18 meses.', 'Gerente de Producción', '2025-06-01', 'identificado', 'Pendiente de aprobación presupuestal.', 'Oportunidad de alta mejora de eficiencia.');

-- RECURSOS
INSERT INTO recursos (tipo_recurso, nombre_recurso, area, estado_actual, cantidad_actual, capacidad_utilizada, necesidad_adicional, cantidad_requerida, justificacion, prioridad, fecha_evaluacion, responsable, costo_estimado, estado_solicitud, observaciones) VALUES
('humano', 'Técnicos de calidad', 'Calidad', 'insuficiente', '3 técnicos', 95, true, '2 técnicos adicionales', 'Aumento de volumen de producción en 30%. Tiempos de inspección comprometidos.', 'alta', '2024-11-15', 'Jefe de Calidad', 80000, 'aprobado', 'Reclutamiento en proceso. Inicio proyectado: Enero 2025.'),
('infraestructura', 'Equipo de medición dimensional', 'Calidad', 'requiere_mejora', '2 equipos', 100, true, '1 equipo adicional', 'Equipos actuales con uso continuo. Requiere reducir tiempos de espera.', 'media', '2024-10-30', 'Jefe de Calidad', 25000, 'aprobado', 'Compra autorizada. Entrega prevista: Diciembre 2024.'),
('tecnologico', 'Software de gestión documental', 'Calidad', 'adecuado', '50 licencias', 70, false, NULL, NULL, 'baja', '2024-11-01', 'Representante de Calidad', NULL, NULL, 'Sistema funcionando correctamente. Capacidad suficiente.'),
('infraestructura', 'Espacio de almacenamiento', 'Logística', 'insuficiente', '500 m²', 98, true, '200 m² adicionales', 'Crecimiento de inventario de producto terminado. Riesgo de mezclas.', 'alta', '2024-11-20', 'Jefe de Logística', 150000, 'pendiente', 'Evaluando arriendo de bodega externa vs. ampliación.'),
('financiero', 'Presupuesto para capacitación', 'RRHH', 'adecuado', '50000 USD/año', 65, false, NULL, NULL, 'baja', '2024-09-01', 'Director RRHH', NULL, NULL, 'Presupuesto suficiente para plan anual.'),
('humano', 'Auditor interno certificado', 'Calidad', 'disponible', '1 auditor', 80, true, '1 auditor adicional', 'Programa de auditorías internas ampliado. Un solo auditor insuficiente.', 'media', '2024-11-10', 'Representante de Calidad', 15000, 'en_proceso', 'Certificación de colaborador interno en curso.');

-- SEGUIMIENTO Y MEDICIÓN
INSERT INTO seguimiento_medicion (fecha_medicion, tipo_medicion, nombre_medicion, metodo_medicion, resultado_obtenido, valor_numerico, unidad_medida, cumple_criterio, desviaciones_encontradas, causas_analisis, acciones_tomadas, responsable, proceso_relacionado, observaciones) VALUES
('2024-11-30', 'producto', 'Inspección dimensional lote 2024-450', 'Calibrador digital certificado', 'Conforme', 99.8, '%', true, NULL, NULL, NULL, 'Inspector QC', 'Control de calidad', 'Lote aprobado para despacho.'),
('2024-11-28', 'proceso', 'Tiempo de ciclo línea producción 1', 'Cronometraje y análisis de tiempos', 'Dentro de especificación', 12.3, 'minutos', true, 'Leve variabilidad en turno nocturno', 'Cambio de operador sin supervisión', 'Refuerzo de supervisión en turno nocturno', 'Supervisor de Producción', 'Producción', 'Seguimiento semanal implementado.'),
('2024-11-25', 'satisfaccion_cliente', 'Encuesta de satisfacción mensual', 'Encuesta online post-venta', 'Satisfactorio', 92.5, '%', true, NULL, NULL, NULL, 'Jefe de Servicio al Cliente', 'Servicio al cliente', 'Meta superada (90%). Felicitaciones recibidas por atención.'),
('2024-11-20', 'producto', 'Inspección lote 2024-438', 'Muestreo según plan AQL 2.5', 'No conforme', 94.5, '%', false, '5.5% de producto fuera de especificación de peso', 'Descalibración de dosificadora', 'Calibración de equipo. Lote retenido y reprocesado.', 'Inspector QC', 'Control de calidad', 'Acción correctiva AC-2024-045 abierta.'),
('2024-11-15', 'sistema', 'Auditoría interna de documentos', 'Checklist de verificación ISO 9001', 'Conforme con observaciones', 95.0, '%', true, '2 documentos sin control de versiones', 'Error en distribución de copias controladas', 'Implementación de sistema digital de control de documentos', 'Representante de Calidad', 'Gestión documental', 'Mejora en implementación.');

-- DESEMPEÑO DE PROCESOS
INSERT INTO desempeno_procesos (periodo, nombre_proceso, responsable_proceso, eficacia, eficiencia, productos_conformes, productos_no_conformes, porcentaje_conformidad, tiempo_ciclo_promedio, unidad_tiempo, capacidad_instalada, capacidad_utilizada, tendencia, problemas_identificados, mejoras_implementadas, objetivos_cumplidos, observaciones) VALUES
('Q4-2024', 'Producción Línea 1', 'Supervisor Línea 1', 96.5, 89.0, 9650, 350, 96.5, 12.5, 'minutos', 12000, 10000, 'mejora', 'Variabilidad en turno nocturno. Desgaste de herramientas.', 'Supervisión reforzada. Plan de mantenimiento preventivo actualizado.', true, 'Proceso con buen desempeño. Mejora continua activa.'),
('Q4-2024', 'Control de Calidad', 'Jefe de Calidad', 98.0, 85.0, 14700, 300, 98.0, 15.0, 'minutos', NULL, NULL, 'estable', 'Tiempos de inspección incrementados por aumento de volumen.', 'Solicitud de 2 inspectores adicionales aprobada.', true, 'Cumplimiento de objetivos. Capacidad comprometida.'),
('Q4-2024', 'Compras', 'Gerente de Compras', 92.0, 88.0, NULL, NULL, NULL, 5.0, 'días', NULL, NULL, 'estable', 'Retrasos con proveedor de embalajes.', 'Proveedor alternativo calificado como backup.', true, 'Proceso estable. Gestión de proveedores efectiva.'),
('Q4-2024', 'Servicio al Cliente', 'Jefe de Servicio', 95.0, 92.0, NULL, NULL, NULL, 2.5, 'días', NULL, NULL, 'mejora', NULL, 'Implementación de sistema de tickets. Capacitación en resolución.', true, 'Mejora significativa vs. Q3. Meta de tiempo de respuesta superada.'),
('Q4-2024', 'Ventas', 'Director Comercial', 88.0, 82.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'deterioro', 'Aumento de competencia. Pérdida de 3 clientes en el trimestre.', 'Plan de fidelización en desarrollo. Revisión de estrategia de precios.', false, 'Requiere atención. Objetivos de ventas no cumplidos (90% vs. 100% meta).');

-- PARTES INTERESADAS
INSERT INTO partes_interesadas (nombre, tipo, necesidades_expectativas, requisitos_aplicables, metodo_comunicacion, frecuencia_comunicacion, ultimo_contacto, nivel_satisfaccion, nivel_influencia, nivel_interes, responsable_relacion, observaciones) VALUES
('Distribuidora XYZ S.A.', 'cliente', 'Calidad consistente, entregas puntuales, precios competitivos, certificación ISO', 'ISO 9001, Especificaciones técnicas productos, Tiempos de entrega máximo 10 días', 'Reuniones presenciales, correo, portal web', 'Mensual', '2024-11-28', 5, 'alto', 'alto', 'Director Comercial', 'Cliente estratégico (30% de ventas). Relación excelente.'),
('Empleados - Área Producción', 'empleado', 'Condiciones seguras de trabajo, capacitación, estabilidad laboral, equipos adecuados', 'Normativa laboral, ISO 45001 (en implementación), Convenio colectivo', 'Reuniones de área, carteleras, correo corporativo', 'Semanal', '2024-12-05', 4, 'alto', 'alto', 'Director RRHH', 'Clima laboral positivo. Plan de capacitación activo.'),
('Superintendencia de Industria', 'regulador', 'Cumplimiento normativo, trazabilidad de productos, respuesta a quejas consumidores', 'Normativa técnica sectorial, Normas de etiquetado, Código de protección al consumidor', 'Informes oficiales, inspecciones', 'Según requerimiento', '2024-08-15', NULL, 'alto', 'medio', 'Gerente General', 'Sin hallazgos en última inspección. Cumplimiento total.'),
('Suministros Industriales S.A.', 'proveedor', 'Volumen de compra estable, pago oportuno, comunicación fluida', 'Acuerdo comercial, Especificaciones técnicas, Certificado de calidad', 'Correo, reuniones trimestrales', 'Quincenal', '2024-12-01', 5, 'medio', 'alto', 'Gerente de Compras', 'Proveedor estratégico. Relación a largo plazo (8 años).'),
('Accionistas', 'accionista', 'Rentabilidad, crecimiento sostenible, gestión de riesgos, cumplimiento regulatorio', 'Estatutos sociales, Código de gobierno corporativo', 'Asambleas, informes de gestión', 'Trimestral', '2024-11-15', 4, 'alto', 'alto', 'Gerente General', 'Resultados positivos 2024. Aprobación de inversiones estratégicas.'),
('Comunidad Local', 'comunidad', 'Empleo local, responsabilidad ambiental, proyección social', 'Normativa ambiental, Plan de gestión social', 'Actividades comunitarias, comunicados', 'Semestral', '2024-10-10', 4, 'bajo', 'medio', 'Gerente General', 'Relación cordial. Participación en programa de becas educativas.');

-- ============================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- ============================================

CREATE INDEX IF NOT EXISTS idx_compromisos_revision ON compromisos(revision_id);
CREATE INDEX IF NOT EXISTS idx_compromisos_estado ON compromisos(estado);
CREATE INDEX IF NOT EXISTS idx_compromisos_responsable ON compromisos(responsable);
CREATE INDEX IF NOT EXISTS idx_evidencias_revision ON evidencias(revision_id);
CREATE INDEX IF NOT EXISTS idx_evidencias_compromiso ON evidencias(compromiso_id);
CREATE INDEX IF NOT EXISTS idx_objetivos_periodo ON objetivos_calidad(periodo);
CREATE INDEX IF NOT EXISTS idx_objetivos_estado ON objetivos_calidad(estado);
CREATE INDEX IF NOT EXISTS idx_riesgos_tipo ON riesgos_oportunidades(tipo);
CREATE INDEX IF NOT EXISTS idx_riesgos_estado ON riesgos_oportunidades(estado);
CREATE INDEX IF NOT EXISTS idx_recursos_tipo ON recursos(tipo_recurso);
CREATE INDEX IF NOT EXISTS idx_recursos_estado_solicitud ON recursos(estado_solicitud);
