-- ============================================
-- MIGRACIÓN: Actualizar tabla revisiones existente
-- y crear nuevas tablas para el sistema completo
-- ============================================

-- 1. ACTUALIZAR TABLA REVISIONES (agregar nuevas columnas)
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS participantes TEXT[];
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'abierta';
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS carpeta_onedrive TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_auditorias TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_clientes TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_procesos TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_acciones_previas TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_cambios_externos TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_proveedores TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_recursos TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_riesgos TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS analisis_oportunidades TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS decisiones_sgc TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS decisiones_productos TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS necesidades_recursos TEXT;
ALTER TABLE revisiones ADD COLUMN IF NOT EXISTS porcentaje_cumplimiento NUMERIC DEFAULT 0;

-- Renombrar columna si existe (compatibilidad)
DO $$ 
BEGIN
  IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='revisiones' AND column_name='sharepoint_folder_url') THEN
    ALTER TABLE revisiones RENAME COLUMN sharepoint_folder_url TO carpeta_drive;
  END IF;
END $$;

-- 2. CREAR TABLA: COMPROMISOS
CREATE TABLE IF NOT EXISTS compromisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id BIGINT REFERENCES revisiones(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  descripcion TEXT NOT NULL,
  responsable TEXT NOT NULL,
  fecha_compromiso DATE NOT NULL,
  fecha_cumplimiento DATE,
  estado TEXT DEFAULT 'pendiente',
  evidencia_url TEXT,
  observaciones TEXT
);

-- 3. CREAR TABLA: AUDITORÍAS
CREATE TABLE IF NOT EXISTS auditorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_auditoria DATE NOT NULL,
  tipo TEXT,
  proceso_auditado TEXT,
  auditor_lider TEXT,
  hallazgos_totales INT DEFAULT 0,
  conformidades INT DEFAULT 0,
  no_conformidades_mayores INT DEFAULT 0,
  no_conformidades_menores INT DEFAULT 0,
  observaciones_count INT DEFAULT 0,
  estado_general TEXT,
  resumen TEXT,
  archivo_informe TEXT
);

-- 4. CREAR TABLA: QUEJAS Y RECLAMOS
CREATE TABLE IF NOT EXISTS quejas_reclamos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_recepcion DATE NOT NULL,
  tipo TEXT,
  cliente TEXT,
  producto_servicio TEXT,
  descripcion TEXT,
  estado TEXT,
  fecha_resolucion DATE,
  satisfaccion_resolucion INT,
  acciones_tomadas TEXT
);

-- 5. CREAR TABLA: INDICADORES
CREATE TABLE IF NOT EXISTS indicadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  periodo TEXT,
  nombre_indicador TEXT NOT NULL,
  categoria TEXT,
  valor_actual NUMERIC,
  valor_meta NUMERIC,
  unidad_medida TEXT,
  cumplimiento NUMERIC,
  tendencia TEXT,
  responsable TEXT
);

-- 6. CREAR TABLA: NO CONFORMIDADES
CREATE TABLE IF NOT EXISTS no_conformidades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  fecha_deteccion DATE NOT NULL,
  tipo TEXT,
  severidad TEXT,
  proceso_afectado TEXT,
  descripcion TEXT,
  causa_raiz TEXT,
  accion_correctiva TEXT,
  responsable TEXT,
  fecha_cierre DATE,
  estado TEXT,
  eficacia_verificada BOOLEAN DEFAULT false
);

-- 7. CREAR TABLA: PROVEEDORES
CREATE TABLE IF NOT EXISTS proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  nombre_proveedor TEXT NOT NULL,
  categoria TEXT,
  calificacion_actual NUMERIC,
  fecha_evaluacion DATE,
  criterios_evaluacion JSONB,
  estado TEXT,
  incidentes_totales INT DEFAULT 0,
  observaciones TEXT
);

-- 8. CREAR TABLA: EVIDENCIAS
CREATE TABLE IF NOT EXISTS evidencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id BIGINT REFERENCES revisiones(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  nombre_archivo TEXT NOT NULL,
  tipo_archivo TEXT,
  url_drive TEXT,
  url_onedrive TEXT,
  categoria TEXT,
  descripcion TEXT,
  subido_por TEXT
);

-- ============================================
-- HABILITAR RLS EN NUEVAS TABLAS
-- ============================================

ALTER TABLE compromisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE quejas_reclamos ENABLE ROW LEVEL SECURITY;
ALTER TABLE indicadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE no_conformidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidencias ENABLE ROW LEVEL SECURITY;

-- Políticas temporales para prototipo
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'compromisos' AND policyname = 'Acceso total temporal') THEN
    CREATE POLICY "Acceso total temporal" ON compromisos FOR ALL USING (true) WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'auditorias' AND policyname = 'Acceso total temporal') THEN
    CREATE POLICY "Acceso total temporal" ON auditorias FOR ALL USING (true) WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'quejas_reclamos' AND policyname = 'Acceso total temporal') THEN
    CREATE POLICY "Acceso total temporal" ON quejas_reclamos FOR ALL USING (true) WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'indicadores' AND policyname = 'Acceso total temporal') THEN
    CREATE POLICY "Acceso total temporal" ON indicadores FOR ALL USING (true) WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'no_conformidades' AND policyname = 'Acceso total temporal') THEN
    CREATE POLICY "Acceso total temporal" ON no_conformidades FOR ALL USING (true) WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'proveedores' AND policyname = 'Acceso total temporal') THEN
    CREATE POLICY "Acceso total temporal" ON proveedores FOR ALL USING (true) WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'evidencias' AND policyname = 'Acceso total temporal') THEN
    CREATE POLICY "Acceso total temporal" ON evidencias FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================
-- FUNCIONES
-- ============================================

-- Función para actualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para revisiones
DROP TRIGGER IF EXISTS update_revisiones_updated_at ON revisiones;
CREATE TRIGGER update_revisiones_updated_at 
  BEFORE UPDATE ON revisiones
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Función para calcular cumplimiento
CREATE OR REPLACE FUNCTION calcular_cumplimiento_revision(revision_id_param BIGINT)
RETURNS NUMERIC AS $$
DECLARE
    total_compromisos INT;
    compromisos_completados INT;
    porcentaje NUMERIC;
BEGIN
    SELECT COUNT(*) INTO total_compromisos 
    FROM compromisos 
    WHERE revision_id = revision_id_param;
    
    IF total_compromisos = 0 THEN
        RETURN 0;
    END IF;
    
    SELECT COUNT(*) INTO compromisos_completados 
    FROM compromisos 
    WHERE revision_id = revision_id_param AND estado = 'completado';
    
    porcentaje := (compromisos_completados::NUMERIC / total_compromisos::NUMERIC) * 100;
    
    RETURN ROUND(porcentaje, 2);
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- DATOS DE DEMOSTRACIÓN (solo si las tablas están vacías)
-- ============================================

-- AUDITORÍAS
INSERT INTO auditorias (fecha_auditoria, tipo, proceso_auditado, auditor_lider, hallazgos_totales, conformidades, no_conformidades_mayores, no_conformidades_menores, observaciones_count, estado_general, resumen)
SELECT * FROM (VALUES
  ('2024-11-15', 'interna', 'Producción', 'Carlos Ramírez', 12, 8, 1, 2, 1, 'requiere_mejoras', 'Se identificó falta de calibración en equipos de medición. Plan de acción en marcha.'),
  ('2024-10-20', 'interna', 'Compras', 'María González', 8, 7, 0, 1, 0, 'satisfactorio', 'Proceso de compras funcionando correctamente. Mejora en tiempos de respuesta.'),
  ('2024-09-10', 'certificacion', 'Sistema de Gestión Completo', 'Organismo Certificador ABC', 15, 12, 0, 2, 1, 'satisfactorio', 'Certificación ISO 9001 renovada exitosamente. Observaciones menores cerradas.')
) AS v
WHERE NOT EXISTS (SELECT 1 FROM auditorias LIMIT 1);

-- QUEJAS Y RECLAMOS
INSERT INTO quejas_reclamos (fecha_recepcion, tipo, cliente, producto_servicio, descripcion, estado, fecha_resolucion, satisfaccion_resolucion, acciones_tomadas)
SELECT * FROM (VALUES
  ('2024-11-28', 'queja', 'Distribuidora XYZ', 'Producto A', 'Embalaje dañado en envío', 'resuelta', '2024-12-01', 4, 'Se reenvió producto con embalaje reforzado. Cliente satisfecho.'),
  ('2024-11-20', 'reclamo', 'Cliente ABC S.A.', 'Servicio de mantenimiento', 'Demora en respuesta técnica', 'resuelta', '2024-11-25', 5, 'Se asignó técnico dedicado. Problema resuelto en 24h.'),
  ('2024-11-15', 'sugerencia', 'Empresa DEF', 'Portal web', 'Mejorar interfaz de pedidos', 'en_analisis', NULL, NULL, 'Sugerencia en evaluación por equipo de TI.'),
  ('2024-11-10', 'felicitacion', 'Corporación GHI', 'Atención al cliente', 'Excelente servicio de Sandra Pérez', 'cerrada', '2024-11-10', 5, 'Reconocimiento interno a colaboradora destacada.'),
  ('2024-10-30', 'queja', 'Minorista JKL', 'Producto B', 'Producto no conforme a especificaciones', 'resuelta', '2024-11-05', 3, 'Análisis de causa raíz completado. Lote retirado y reemplazado.')
) AS v
WHERE NOT EXISTS (SELECT 1 FROM quejas_reclamos LIMIT 1);

-- INDICADORES
INSERT INTO indicadores (periodo, nombre_indicador, categoria, valor_actual, valor_meta, unidad_medida, cumplimiento, tendencia, responsable)
SELECT * FROM (VALUES
  ('Q4-2024', 'Índice de Satisfacción del Cliente', 'satisfaccion', 92.5, 90.0, '%', 102.8, 'mejora', 'Director Comercial'),
  ('Q4-2024', 'Productos No Conformes', 'calidad', 2.1, 3.0, '%', 130.0, 'mejora', 'Jefe de Calidad'),
  ('Q4-2024', 'Cumplimiento de Entregas', 'produccion', 94.3, 95.0, '%', 99.3, 'estable', 'Jefe de Producción'),
  ('Q4-2024', 'Tiempo Promedio de Respuesta a Quejas', 'satisfaccion', 2.5, 3.0, 'días', 120.0, 'mejora', 'Servicio al Cliente'),
  ('Q4-2024', 'Eficiencia de Procesos', 'produccion', 87.0, 85.0, '%', 102.4, 'mejora', 'Gerente de Operaciones'),
  ('Q4-2024', 'Rotación de Personal', 'recursos_humanos', 8.5, 10.0, '%', 117.6, 'mejora', 'Director de RRHH'),
  ('Q4-2024', 'Cumplimiento de Acciones Correctivas', 'calidad', 88.0, 95.0, '%', 92.6, 'deterioro', 'Jefe de Calidad')
) AS v
WHERE NOT EXISTS (SELECT 1 FROM indicadores LIMIT 1);

-- NO CONFORMIDADES
INSERT INTO no_conformidades (fecha_deteccion, tipo, severidad, proceso_afectado, descripcion, causa_raiz, accion_correctiva, responsable, fecha_cierre, estado, eficacia_verificada)
SELECT * FROM (VALUES
  ('2024-11-25', 'proceso', 'menor', 'Control de calidad', 'Registro incompleto en formato QC-001', 'Falta de capacitación en nuevo formato', 'Capacitación al equipo de QC. Actualización de instructivo.', 'Jefe de Calidad', '2024-12-02', 'cerrada', true),
  ('2024-11-18', 'producto', 'mayor', 'Producción - Línea 2', 'Lote 2024-11-450 fuera de especificación dimensional', 'Desgaste de herramienta de corte no detectado', 'Implementar verificación diaria de herramientas. Lote retenido.', 'Supervisor de Producción', '2024-11-28', 'cerrada', true),
  ('2024-11-10', 'sistema', 'menor', 'Gestión documental', 'Documentos desactualizados en área de trabajo', 'Falta de control de versiones en distribución', 'Sistema de control digital implementado', 'Representante de Calidad', '2024-11-20', 'cerrada', false),
  ('2024-11-05', 'proceso', 'menor', 'Almacén', 'Inventario con diferencias', 'Error en conteo manual', 'Implementar código de barras para inventario', 'Jefe de Almacén', NULL, 'en_implementacion', false),
  ('2024-10-28', 'producto', 'critica', 'Producción - Línea 1', 'Contaminación detectada en lote 2024-10-380', 'Filtro de aire dañado sin reemplazo oportuno', 'Programa preventivo de mantenimiento reforzado. Lote destruido.', 'Gerente de Producción', '2024-11-10', 'cerrada', true),
  ('2024-10-15', 'sistema', 'menor', 'Capacitación', 'Personal sin capacitación en procedimiento nuevo', 'Programa de inducción no actualizado', 'Actualización de programa. Capacitación programada.', 'RRHH', NULL, 'en_proceso', false)
) AS v
WHERE NOT EXISTS (SELECT 1 FROM no_conformidades LIMIT 1);

-- PROVEEDORES
INSERT INTO proveedores (nombre_proveedor, categoria, calificacion_actual, fecha_evaluacion, criterios_evaluacion, estado, incidentes_totales, observaciones)
SELECT * FROM (VALUES
  ('Suministros Industriales S.A.', 'materias_primas', 92.5, '2024-11-01', '{"calidad": 95, "entrega": 90, "precio": 88, "servicio": 97}', 'aprobado', 1, 'Proveedor estratégico. Incidente menor en octubre resuelto.'),
  ('Transportes Rápidos Ltda.', 'servicios', 78.0, '2024-11-15', '{"calidad": 75, "entrega": 70, "precio": 85, "servicio": 82}', 'condicional', 4, 'Retrasos recurrentes. En período de mejora (3 meses).'),
  ('Empaques Premium', 'materias_primas', 88.0, '2024-10-20', '{"calidad": 92, "entrega": 88, "precio": 82, "servicio": 90}', 'aprobado', 0, 'Desempeño consistente. Sin incidentes en el período.'),
  ('Calibración y Metrología Andina', 'servicios', 96.0, '2024-09-30', '{"calidad": 98, "entrega": 95, "precio": 92, "servicio": 99}', 'aprobado', 0, 'Excelente servicio. Certificaciones al día.'),
  ('Repuestos Industriales XYZ', 'equipos', 65.0, '2024-11-01', '{"calidad": 60, "entrega": 55, "precio": 75, "servicio": 70}', 'no_aprobado', 8, 'Calidad deficiente. Búsqueda de proveedor alternativo en curso.')
) AS v
WHERE NOT EXISTS (SELECT 1 FROM proveedores LIMIT 1);
